//public Class Cats extends Mammals {
//    public void meow(){
//        system.debug('Cats meow...');
//    }
//    Override
//        public void feedWithMilk(){
//            system.debug('Cats feed their babies with milk');
//        }
//}

public Class Cats extends Mammals {
    
    public void meow(){
        system.debug('Cats meow...');
    }
    Override   
      public void feedwithMilk(){
        system.debug('Cats feed their babies with milk...');
    }
}