//public Class Dogs extends Mammals {
//    public void bark(){
//        system.debug('Dogs bark...');
//    }
//    Override
//        public void eat(){
//        System.debug('Dogs eat...');
//        }
//}
//
public Class Dogs extends Mammals {
    public void bark(){
        system.debug('Dogs bark...');
    }
    Override
       public void eat(){
          system.debug('Dogs eat...');
       }     
}